# Generated by Django 4.1.2 on 2022-10-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rewiew_text',
        ),
        migrations.AddField(
            model_name='review',
            name='review_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='review_text',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
