# Generated by Django 4.1.2 on 2022-11-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0002_alter_subject_subject_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('lesson_format', models.IntegerField(choices=[(1, 'ONLINE'), (2, 'OFFLINE')])),
                ('subjects', models.ManyToManyField(blank=True, to='subjects.subject')),
            ],
        ),
    ]
