# Generated by Django 4.1.2 on 2022-11-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_alter_subject_subject_name'),
        ('courses', '0002_course_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subjects',
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ManyToManyField(blank=True, to='subjects.subject'),
        ),
    ]
