# Generated by Django 4.1.2 on 2022-11-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_user_course_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='location',
            field=models.CharField(default='Test City', max_length=50),
            preserve_default=False,
        ),
    ]
