# Generated by Django 4.1.2 on 2022-11-20 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.PositiveSmallIntegerField()),
                ('rating_time', models.DateTimeField(auto_now=True)),
                ('rating_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_authors', to=settings.AUTH_USER_MODEL)),
                ('rating_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_recipients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
