# Generated by Django 4.1.2 on 2022-10-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_value',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
