# Generated by Django 4.1.2 on 2022-11-20 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.IntegerField(choices=[(1, 'Tutor'), (2, 'Student')])),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('contact_mail', models.EmailField(max_length=254, null=True, unique=True)),
                ('phone_number', phone_field.models.PhoneField(max_length=31, null=True)),
                ('about_me', models.TextField(max_length=1000, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_trusted', models.BooleanField(default=False)),
                ('date_of_birth', models.DateField(null=True)),
                ('location', models.CharField(max_length=50)),
                ('profile_picture', models.FileField(blank=True, upload_to='docs/pfp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
