# Generated by Django 4.1.2 on 2022-10-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=16)),
                ('last_name', models.CharField(max_length=16)),
                ('is_student', models.BooleanField()),
                ('is_teacher', models.BooleanField()),
                ('is_verified', models.BooleanField(default=False)),
                ('date_of_birth', models.DateField(null=True)),
                ('location', models.CharField(max_length=32)),
                ('profile_picture', models.FileField(upload_to='')),
            ],
        ),
    ]
