# Generated by Django 4.1.2 on 2022-10-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_sertificates_profile_certificates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.FileField(blank=True, upload_to='docs/pfp'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.IntegerField(blank=True, choices=[('TUTOR', 1), ('STUDENT', 2)]),
        ),
    ]
