# Generated by Django 4.1.2 on 2022-11-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('profiles', '0006_alter_profile_profile_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subjects',
        ),
        migrations.AddField(
            model_name='profile',
            name='courses',
            field=models.ManyToManyField(blank=True, to='courses.course'),
        ),
    ]
