# Generated by Django 4.1.2 on 2022-11-05 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_profile_subjects_profile_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='courses',
        ),
    ]
