# Generated by Django 4.1.2 on 2022-10-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emal', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('first_name', models.CharField(max_length=16)),
                ('last_name', models.CharField(max_length=16)),
                ('is_student', models.BooleanField()),
                ('is_pupil', models.BooleanField()),
                ('is_admin', models.BooleanField()),
                ('is_verified', models.BooleanField()),
                ('date_of_birth', models.DateField(blank=True)),
                ('location', models.CharField(blank=True, max_length=32)),
            ],
        ),
    ]
