# Generated by Django 4.1.2 on 2022-10-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.RenameModel(
            old_name='Test',
            new_name='TestUnit',
        ),
        migrations.CreateModel(
            name='TestManyToMany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ManyToManyField(to='users.testunit')),
            ],
        ),
    ]
