# Generated by Django 4.1.2 on 2022-10-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_sertificate_subject_user_sertificates_user_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sertificate',
            name='document',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='sertificate',
            name='subject',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='testunit',
            name='test_data',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='sertificates',
            field=models.ManyToManyField(to='users.sertificate'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subjects',
            field=models.ManyToManyField(to='users.subject'),
        ),
    ]
