# Generated by Django 4.1.2 on 2022-10-14 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_sertificate_document_alter_sertificate_subject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sertificate',
            old_name='document',
            new_name='document_path',
        ),
        migrations.RenameField(
            model_name='sertificate',
            old_name='subject',
            new_name='subject_name',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='subject_name',
        ),
        migrations.RenameField(
            model_name='testmanytomany',
            old_name='data',
            new_name='test_record',
        ),
    ]
