# Generated by Django 4.1.2 on 2022-10-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_sertificates_remove_user_subjects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='subjects',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_pupil',
            new_name='is_teacher',
        ),
        migrations.AddField(
            model_name='user',
            name='sertificates',
            field=models.ManyToManyField(blank=True, to='users.sertificate'),
        ),
        migrations.AddField(
            model_name='user',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='users.subject'),
        ),
        migrations.AlterField(
            model_name='sertificate',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.DeleteModel(
            name='Certificates',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
