# Generated by Django 4.1.2 on 2022-10-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_subjects_subjects_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='emal',
            new_name='email',
        ),
    ]
