# Generated by Django 4.1.2 on 2022-10-14 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_sertificate_document_path_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestManyToMany',
        ),
        migrations.DeleteModel(
            name='TestUnit',
        ),
    ]
