# Generated by Django 4.1.2 on 2022-10-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_delete_testmanytomany_delete_testunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_data', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='TestManyToMany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_record', models.ManyToManyField(to='users.testunit')),
            ],
        ),
    ]
