# Generated by Django 4.1.2 on 2022-10-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_testunit_testmanytomany'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rewiew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_fname', models.CharField(max_length=16)),
                ('author_lname', models.CharField(max_length=16)),
                ('rating', models.IntegerField()),
                ('text', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='rewiews',
            field=models.ManyToManyField(blank=True, to='users.rewiew'),
        ),
    ]
