# Generated by Django 4.1.2 on 2022-10-14 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rewiew_alter_user_email_user_rewiews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rewiew',
            old_name='text',
            new_name='rewiew_text',
        ),
    ]
