# Generated by Django 4.1.2 on 2022-10-17 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_text_rewiew_rewiew_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sertificate',
            new_name='Certificate',
        ),
    ]
