# Generated by Django 4.1.2 on 2022-10-17 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_email'),
        ('users', '0016_rename_sertificate_certificate'),
    ]

    operations = [
    ]
