# Generated by Django 4.1.2 on 2022-10-17 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_merge_20221017_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmanytomany',
            name='test_record',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_teacher',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rewiews',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sertificates',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subjects',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='Rewiew',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='TestManyToMany',
        ),
        migrations.DeleteModel(
            name='TestUnit',
        ),
    ]
