# Generated by Django 4.1.2 on 2022-11-09 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_recoverycode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
