# Generated by Django 4.1.2 on 2022-11-09 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_rename_is_admin_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='is_admin',
        ),
    ]
