# Generated by Django 4.1.2 on 2022-11-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_path', models.FileField(upload_to='docs/certificates')),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
