# Generated by Django 4.1.2 on 2022-10-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=32)),
                ('document_path', models.FileField(upload_to='')),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
