# Generated by Django 4.1.2 on 2022-10-24 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_alter_certificate_document_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='subject_name',
        ),
    ]
